Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Oslo"
  end
end