heat_template_version: 2021-04-16

description: Template to deploy a VM with floating IP

parameters:
  key_name:
    type: string
    description: Name of key pair
    label: Key name
    default: my_key

resources:
  internal_net:
    type: OS::Neutron::Net

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: internal_net }
      cidr: '10.8.1.0/24'
      dns_nameservers: ['8.8.8.8', '8.8.4.4']
      ip_version: 4

  internal_router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info: { network: ntnu-internal }

  internal_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: internal_router }
      subnet: { get_resource: internal_subnet }

  instance_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: internal_net }
      fixed_ips:
        - subnet_id: { get_resource: internal_subnet }

  my_key:
    type: OS::Nova::KeyPair
    properties:
      save_private_key: true
      name: { get_param: key_name }

  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_resource: my_key }
      image: fe8be799-21f4-489a-9e3f-9b8a2e15c015 # Ubuntu Server 20.04 amd64
      flavor: m1.small
      networks:
        - port: { get_resource: instance_port }

outputs:
  instance_ip:
    description: The IP address of the deployed MV
    value: { get_attr: [my_instance, first_address] }
  private_key:
    description: Private key
    value: { get_attr: [my_key, private_key] }
